use phf;

// TODO Validate: 'input lifetime will be difficult to do with a streaming source (BufRead)
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Token<'input> {
    // Keywords:
    Abort,
    Action,
    Add,
    After,
    All,
    Alter,
    Analyze,
    And,
    // Any,
    As,
    Asc,
    Attach,
    Autoincr,
    Before,
    Begin,
    Between,
    By,
    Cascade,
    Case,
    Cast,
    Check,
    Collate,
    ColumnKw,
    Commit,
    Conflict,
    Constraint,
    Create,
    Cross,
    CurrentDate,
    CurrentTime,
    CurrentTimestamp,
    Database,
    Default,
    Deferrable,
    Deferred,
    Delete,
    Desc,
    Detach,
    Distinct,
    Drop,
    Each,
    Else,
    End,
    Escape,
    Except,
    Exclusive,
    Exists,
    Explain,
    Fail,
    For,
    Foreign,
    From,
    Full,
    // Function,
    Glob,
    Group,
    Having,
    If,
    Ignore,
    Immediate,
    In,
    Index,
    Indexed,
    Initially,
    Inner,
    Insert,
    Instead,
    Intersect,
    Into,
    Is,
    // IsNot,
    IsNull,
    Join,
    Key,
    Left,
    Like,
    Limit,
    Match,
    Natural,
    No,
    Not,
    NotNull,
    Null,
    Of,
    Offset,
    On,
    Or,
    Order,
    Outer,
    Plan,
    Pragma,
    Primary,
    Query,
    Raise,
    Recursive,
    References,
    Regexp,
    Reindex,
    Release,
    Rename,
    Replace,
    Restrict,
    Right,
    Rollback,
    Row,
    Savepoint,
    Select,
    Set,
    Table,
    Temp,
    Then,
    To,
    Transaction,
    Trigger,
    Union,
    Unique,
    Update,
    Using,
    Vacuum,
    Values,
    View,
    Virtual,
    When,
    Where,
    With,
    Without,

    // Identifiers:
    StringLiteral(&'input str),
    Id(&'input str),
    Variable(&'input str),

    // Values:
    Blob(&'input str),
    Integer(&'input str),
    Float(&'input str),

    // Symbols:
    BitAnd,
    BitNot,
    BitOr,
    Comma,
    Concat,
    Dot,
    Equals,
    GreaterThan,
    GreaterEquals,
    LeftParen,
    LeftShift,
    LessEquals,
    LessThan,
    Minus,
    NotEquals,
    Plus,
    Reminder,
    RightParen,
    RightShift,
    Semi,
    Slash,
    Star,
}

#[cfg_attr(rustfmt, rustfmt_skip)]
static KEYWORDS: phf::Map<&'static str, Token<'static>> = phf_map! {
    "ABORT" => Token::Abort,
    "ACTION" => Token::Action,
    "ADD" => Token::Add,
    "AFTER" => Token::After,
    "ALL" => Token::All,
    "ALTER" => Token::Alter,
    "ANALYZE" => Token::Analyze,
    "AND" => Token::And,
    "AS" => Token::As,
    "ASC" => Token::Asc,
    "ATTACH" => Token::Attach,
    "AUTOINCREMENT" => Token::Autoincr,
    "BEFORE" => Token::Before,
    "BEGIN" => Token::Begin,
    "BETWEEN" => Token::Between,
    "BY" => Token::By,
    "CASCADE" => Token::Cascade,
    "CASE" => Token::Case,
    "CAST" => Token::Cast,
    "CHECK" => Token::Check,
    "COLLATE" => Token::Collate,
    "COLUMN" => Token::ColumnKw,
    "COMMIT" => Token::Commit,
    "CONFLICT" => Token::Conflict,
    "CONSTRAINT" => Token::Constraint,
    "CREATE" => Token::Create,
    "CROSS" => Token::Cross,
    "CURRENT_DATE" => Token::CurrentDate,
    "CURRENT_TIME" => Token::CurrentTime,
    "CURRENT_TIMESTAMP" => Token::CurrentTimestamp,
    "DATABASE" => Token::Database,
    "DEFAULT" => Token::Default,
    "DEFERRABLE" => Token::Deferrable,
    "DEFERRED" => Token::Deferred,
    "DELETE" => Token::Delete,
    "DESC" => Token::Desc,
    "DETACH" => Token::Detach,
    "DISTINCT" => Token::Distinct,
    "DROP" => Token::Drop,
    "EACH" => Token::Each,
    "ELSE" => Token::Else,
    "END" => Token::End,
    "ESCAPE" => Token::Escape,
    "EXCEPT" => Token::Except,
    "EXCLUSIVE" => Token::Exclusive,
    "EXISTS" => Token::Exists,
    "EXPLAIN" => Token::Explain,
    "FAIL" => Token::Fail,
    "FOR" => Token::For,
    "FOREIGN" => Token::Foreign,
    "FROM" => Token::From,
    "FULL" => Token::Full,
    "GLOB" => Token::Glob,
    "GROUP" => Token::Group,
    "HAVING" => Token::Having,
    "IF" => Token::If,
    "IGNORE" => Token::Ignore,
    "IMMEDIATE" => Token::Immediate,
    "IN" => Token::In,
    "INDEX" => Token::Index,
    "INDEXED" => Token::Indexed,
    "INITIALLY" => Token::Initially,
    "INNER" => Token::Inner,
    "INSERT" => Token::Insert,
    "INSTEAD" => Token::Instead,
    "INTERSECT" => Token::Intersect,
    "INTO" => Token::Into,
    "IS" => Token::Is,
    "ISNULL" => Token::IsNull,
    "JOIN" => Token::Join,
    "KEY" => Token::Key,
    "LEFT" => Token::Left,
    "LIKE" => Token::Like,
    "LIMIT" => Token::Limit,
    "MATCH" => Token::Match,
    "NATURAL" => Token::Natural,
    "NO" => Token::No,
    "NOT" => Token::Not,
    "NOTNULL" => Token::NotNull,
    "NULL" => Token::Null,
    "OF" => Token::Of,
    "OFFSET" => Token::Offset,
    "ON" => Token::On,
    "OR" => Token::Or,
    "ORDER" => Token::Order,
    "OUTER" => Token::Outer,
    "PLAN" => Token::Plan,
    "PRAGMA" => Token::Pragma,
    "PRIMARY" => Token::Primary,
    "QUERY" => Token::Query,
    "RAISE" => Token::Raise,
    "RECURSIVE" => Token::Recursive,
    "REFERENCES" => Token::References,
    "REGEXP" => Token::Regexp,
    "REINDEX" => Token::Reindex,
    "RELEASE" => Token::Release,
    "RENAME" => Token::Rename,
    "REPLACE" => Token::Replace,
    "RESTRICT" => Token::Restrict,
    "RIGHT" => Token::Right,
    "ROLLBACK" => Token::Rollback,
    "ROW" => Token::Row,
    "SAVEPOINT" => Token::Savepoint,
    "SELECT" => Token::Select,
    "SET" => Token::Set,
    "TABLE" => Token::Table,
    "TEMP" => Token::Temp,
    "TEMPORARY" => Token::Temp,
    "THEN" => Token::Then,
    "TO" => Token::To,
    "TRANSACTION" => Token::Transaction,
    "TRIGGER" => Token::Trigger,
    "UNION" => Token::Union,
    "UNIQUE" => Token::Unique,
    "UPDATE" => Token::Update,
    "USING" => Token::Using,
    "VACUUM" => Token::Vacuum,
    "VALUES" => Token::Values,
    "VIEW" => Token::View,
    "VIRTUAL" => Token::Virtual,
    "WHEN" => Token::When,
    "WHERE" => Token::Where,
    "WITH" => Token::With,
    "WITHOUT" => Token::Without,
};
